#pragma kernel CSMain

// Texture to which depth values will be written
RWTexture2D<float> Result;

// Texture read from the camera's depth
Texture2D<float> DepthTexture;

// Camera's near and far clipping planes
float NearClip;
float FarClip;

[numthreads(32, 32, 1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // Read depth value from the depth texture
    float depth = DepthTexture[id.xy];
    Result[id.xy] = float4(depth, depth, depth, 1.0);
}